name: Create the files.

on:
  push:

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      
      - name: move the file
        run: |
          ls
          mv ./instance-contents/new-stack.yml ./.github/stacks/stack.yml
          rm ./README.md
          mv ./instance-contents/README.md ./README.md
          rm -r ./instance-contents
      
      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added scaffolding and readme."
          git push

